:Author: Alexander Infantino
:Email: infantinoalex@gmail.com
:Date: 15/11/2018
:Revision: 1.0.0
:License: Public Domain

= Project: AirAlign: Soft Robotic Suit

Describe your project

Contains code to interact with solenoid, pressure sensor, and accelerometer that interacts with the soft robotic suit.

== Step 1: Installation



== Step 2: Assemble the circuit



== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

VestPrototype
  
....
 VestPrototype                => Arduino sketch folder
  ├── VestPrototype.ino       => main Arduino file
  ├── schematics.png      => an image of the required schematics
  ├── layout.png          =>  an image of the layout
  └── ReadMe.adoc         => this file
....

=== License



=== Contributing
To contribute to this project please contact AgentBurt_MacklinFBI https://id.arduino.cc/AgentBurt_MacklinFBI

=== BOM

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10
| L1 | Red LED        | 2345-asdf   | 5
| A1 | Arduino Zero   | ABX00066    | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
